port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: "jdbc:h2:~/test"
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa.hibernate.ddl-auto: create